### ISSUE TITLE
about "Stain.Rainbow"

### ISSUE THREAD

**Issue by hjunqq** [HellPie/HellPie.Revit.PrismDemo#1]
Hi :
I find your post in thebuildingcoder and i want to learn your codes, after I clone and compile the codes, it gives the error "cannot find Stain"

```c#
using Stain.Rainbow;
using Stain.Rainbow.Data;
using Stain.Rainbow.Data.Internal;
using Tab = Stain.Rainbow.Data.Tab;
```
 
can you tell me how to fix it ?

**Comment by HellPie** [comment]
You can safely strip that code out and replace the [`new Rainbow() {...};`](https://github.com/HellPie/HellPie.Revit.PrismDemo/blob/main/HellPie.Revit.PrismDemo/App.cs#L32-L63) part of the code in that file with the classic way to create buttons in the Ribbon.

Rainbow is an internal library I wrote at the company I work for, it's not open source, I used it because for the purpose of the demo it doesn't matter how the buttons are created or how the demo runs, it's meant to be a general idea of how to structure code for using the Prism library.

The bulk of the code is in the [`*.Prism`](https://github.com/HellPie/HellPie.Revit.PrismDemo/tree/main/HellPie.Revit.PrismDemo/Prism) namespace and in the various commands and XAML files. The `App` class itself handles registrations of ViewModels but beyond that it serves very little purpose for this demo project.
